version: "3"

services:
  nginx:
    image: banian/nginx-extras
    ports:
      - 8089:80
    volumes:
      - ./:/app
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - app
    networks:
      - net

  app:
    build: docker/php
    ports:
      -  9009:9000
    volumes:
      - ./:/app
    environment:
      PHP_IDE_CONFIG: serverName=gk
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.255.0/28